### ISSUE TITLE
How to get the named entity type in wiki dataset?

### ISSUE THREAD

**Issue by RedVelvetCake21** [lhz-97/Multi-Entity-Collaborative-Relation-Extraction#1]
I saw that there are 18 ner labels in config.py and I just have the original dataset without the entity ner labels.
How did you get the entity type using these labels with wiki dataset or did you use any tools to preprocess? Could you help me plz?

**Comment by lhz-97** [comment]
We use a crawler on the Wiki to get the corresponding entity type. For each entity change the link of the page.

**Comment by RedVelvetCake21** [comment]
Thanks!
